-- SKILLFORGE AI — SUPABASE POSTGRESQL RELATIONAL SCHEMA

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. ROADMAPS TABLE (JSONB SKILL GRAPH)
CREATE TABLE IF NOT EXISTS roadmaps (
    id SERIAL PRIMARY KEY,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    target_role VARCHAR(255) NOT NULL,
    current_skills TEXT,
    title VARCHAR(255) NOT NULL,
    milestones_json JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. SKILL AUDITS TABLE (METACOGNITIVE CONFIDENCE GAP)
CREATE TABLE IF NOT EXISTS skill_audits (
    id SERIAL PRIMARY KEY,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    roadmap_id INT REFERENCES roadmaps(id) ON DELETE CASCADE,
    topic VARCHAR(255) NOT NULL,
    confidence_rating INT CHECK (confidence_rating BETWEEN 1 AND 5),
    is_correct BOOLEAN NOT NULL,
    overconfidence_delta INT DEFAULT 0,
    remedial_lesson TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. BADGES TABLE (HMAC-SHA256 CRYPTOGRAPHIC SIGNATURE)
CREATE TABLE IF NOT EXISTS badges (
    id SERIAL PRIMARY KEY,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    roadmap_id INT REFERENCES roadmaps(id) ON DELETE CASCADE,
    badge_title VARCHAR(255) NOT NULL,
    hmac_signature VARCHAR(255) UNIQUE NOT NULL,
    issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
